apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: basic-task
spec:
  steps:
  - name: echo-helloworld
    image: icr.io/continuous-delivery/pipeline/pipeline-base-image
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
