apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: basic-task
spec:
  steps:
  - name: echo-helloworld1
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld2
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld3
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld4
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld5
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld6
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld7
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld8
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld9
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld10
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld11
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld12
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld13
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld14
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld15
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld16
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld17
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld18
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld19
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld20
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld21
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld21
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld23
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld24
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld25
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld26
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld27
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld28
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld29
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld30
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld31
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld32
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld33
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld34
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld35
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld36
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld37
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld38
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld39
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld40
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld41
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld42
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld43
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld44
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld45
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld46
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld47
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld48
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld49
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
  - name: echo-helloworld50
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
    - echo hello world;
